[env:seeed-xiao-nrf54l15]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git#9ba53b691fb007d9c1b8fd37600cc71d6702125a
platform_packages = toolchain-gccarmnoneeabi@~1.140201.0
framework = zephyr
board = seeed-xiao-nrf54l15
monitor_speed = 115200
