import SwiftUI
import UniformTypeIdentifiers
import VoxaCore
import VoxaRuntime

func presentationImportFailureMessage(
    errorDescription: String,
    retainsCurrentPresentation: Bool
) -> String {
    let trimmedDescription = errorDescription.trimmingCharacters(in: .whitespacesAndNewlines)
    guard retainsCurrentPresentation else { return trimmedDescription }
    let sentence = trimmedDescription.hasSuffix(".")
        ? trimmedDescription
        : "\(trimmedDescription)."
    return "\(sentence) Your current presentation is unchanged."
}

func simplePresentationTimingDescription(
    targetDurationSeconds: Int,
    slideCount: Int
) -> String {
    guard slideCount > 0 else { return "Divide the target evenly" }
    guard targetDurationSeconds >= slideCount else {
        let minimumMinutes = Int(ceil(Double(slideCount) / 60))
        return "Increase target to at least \(minimumMinutes) min"
    }
    let average = Double(targetDurationSeconds) / Double(slideCount)
    return "Divide evenly · about \(TimeInterval(average).clockString) per slide"
}

func disconnectedPresentationBandDetail(transitionCueEnabled: Bool) -> String? {
    transitionCueEnabled
        ? "Not connected · on-screen guide continues without wrist cues"
        : nil
}

struct SessionSetupView: View {
    @Environment(AppModel.self) private var model
    @Environment(\.dismiss) private var dismiss
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @Environment(\.dynamicTypeSize) private var dynamicTypeSize
    @State private var sessionMode: SessionMode
    @State private var name = "Practice Session"
    @State private var targetMinutes = 5.0
    @State private var minimumWPM = 130.0
    @State private var maximumWPM = 160.0
    @State private var advancedCuesExpanded = false
    @State private var emergencyBuzzerEnabled = false
    @State private var presentationImporterPresented = false
    @State private var isImportingPresentation = false
    @State private var importedFileName: String?
    @State private var importedSlides: [DeckSlide] = []
    @State private var presentationImportError: String?
    @State private var timingMode = PresentationTimingMode.even
    @State private var customSlideDurations: [Int] = []
    @State private var transitionCueEnabled = true
    @State private var coachingOptionsExpanded = false
    @State private var autoGeneratedSessionName: String?

    init(initialMode: SessionMode) {
        _sessionMode = State(initialValue: initialMode)
    }

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    ScreenTitle(
                        eyebrow: "New session",
                        title: sessionMode == .powerPoint ? "Guide your presentation" : "Set your coaching target",
                        subtitle: sessionMode == .powerPoint
                            ? "Cue keeps each slide on time while pace and filler coaching continues."
                            : "Cue listens through this iPhone and coaches pace, fillers, and timing."
                    )
                    sessionTypeCard
                    basicsCard
                    if sessionMode == .powerPoint {
                        presentationCard
                        coachingOptionsToggle
                        if coachingOptionsExpanded {
                            paceCard
                            cueCard
                            overtimeSafetyCard
                        }
                    } else {
                        paceCard
                        cueCard
                        overtimeSafetyCard
                    }
                    preflightCard
                    VStack(alignment: .leading, spacing: 9) {
                        VoxaButton(
                            title: beginButtonTitle,
                            symbol: "arrow.up.right",
                            style: .primary,
                            disabled: startDisabled,
                            action: begin
                        )
                        if let startDisabledReason {
                            Label(startDisabledReason, systemImage: "info.circle")
                                .font(.cueCaption)
                                .foregroundStyle(CueTheme.secondaryInk)
                                .padding(.horizontal, 4)
                        }
                    }
                }
                .padding(.horizontal, 20)
                .padding(.vertical, 22)
            }
            .background(CueTheme.canvas)
            .navigationTitle("Session setup")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
            }
            .fileImporter(
                isPresented: $presentationImporterPresented,
                allowedContentTypes: presentationContentTypes,
                allowsMultipleSelection: false,
                onCompletion: handlePresentationImport
            )
            .onChange(of: targetMinutes) { _, _ in
                if !canAllocateEverySlide {
                    timingMode = .even
                }
                if timingMode == .even { resetCustomTimingEvenly() }
            }
        }
    }

    private var sessionTypeCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 14) {
                CueSectionLabel(text: "Session type", color: CueTheme.signal)
                sessionTypeRow(
                    mode: .freeSpeaking,
                    title: "Free speaking",
                    detail: "Pace, fillers, and overall timing",
                    symbol: "waveform"
                )
                sessionTypeRow(
                    mode: .powerPoint,
                    title: "Presentation",
                    detail: "Add timed cues for every slide",
                    symbol: "rectangle.stack"
                )
            }
        }
    }

    private func sessionTypeRow(
        mode: SessionMode,
        title: String,
        detail: String,
        symbol: String
    ) -> some View {
        Button {
            withAnimation(CueMotion.quick(reduceMotion: reduceMotion)) {
                sessionMode = mode
            }
        } label: {
            HStack(spacing: 12) {
                Image(systemName: symbol)
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundStyle(sessionMode == mode ? Color.white : CueTheme.signal)
                    .frame(width: 36, height: 36)
                    .background(sessionMode == mode ? CueTheme.signal : CueTheme.signalSoft)
                    .clipShape(Circle())
                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                        .foregroundStyle(CueTheme.ink)
                    Text(detail)
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.secondaryInk)
                }
                Spacer(minLength: 8)
                Image(systemName: sessionMode == mode ? "checkmark.circle.fill" : "circle")
                    .foregroundStyle(sessionMode == mode ? CueTheme.signal : CueTheme.border)
            }
            .padding(12)
            .background(sessionMode == mode ? CueTheme.signalSoft.opacity(0.72) : CueTheme.canvas.opacity(0.6))
            .clipShape(RoundedRectangle(cornerRadius: CueTheme.Radius.small, style: .continuous))
        }
        .buttonStyle(.plain)
        .accessibilityAddTraits(sessionMode == mode ? .isSelected : [])
    }

    private var basicsCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 18) {
                CueSectionLabel(text: "Session", color: CueTheme.signal)
                TextField("Session name", text: $name)
                    .font(.cueBody)
                    .padding(15)
                    .background(CueTheme.canvas.opacity(0.72))
                    .clipShape(RoundedRectangle(cornerRadius: CueTheme.Radius.small, style: .continuous))
                    .overlay {
                        RoundedRectangle(cornerRadius: CueTheme.Radius.small, style: .continuous)
                            .stroke(CueTheme.border, lineWidth: 0.75)
                    }
                    .textInputAutocapitalization(.sentences)
                    .submitLabel(.done)

                Stepper(value: $targetMinutes, in: 1...30, step: 1) {
                    if dynamicTypeSize.isAccessibilitySize {
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Target duration")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .foregroundStyle(CueTheme.ink)
                            Text("\(Int(targetMinutes)) minutes")
                                .font(.cueCaption.monospacedDigit())
                                .foregroundStyle(CueTheme.signal)
                        }
                    } else {
                        HStack(spacing: 12) {
                            VStack(alignment: .leading, spacing: 4) {
                                Text("Target duration")
                                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                    .foregroundStyle(CueTheme.ink)
                                Text("Drives private timing reminders")
                                    .font(.cueCaption)
                                    .foregroundStyle(CueTheme.secondaryInk)
                            }
                            Spacer(minLength: 8)
                            Text("\(Int(targetMinutes)) min")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold).monospacedDigit())
                                .foregroundStyle(CueTheme.signal)
                        }
                    }
                }
            }
        }
    }

    private var presentationCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 17) {
                CueSectionLabel(text: "Presentation", color: CueTheme.signal)

                if isImportingPresentation {
                    HStack(spacing: 12) {
                        ProgressView()
                            .tint(CueTheme.signal)
                        Text("Reading slides on this iPhone…")
                            .font(.system(.subheadline, design: .rounded, weight: .semibold))
                            .foregroundStyle(CueTheme.ink)
                    }
                    .frame(maxWidth: .infinity, minHeight: 64, alignment: .leading)
                } else if importedSlides.isEmpty {
                    VStack(alignment: .leading, spacing: 12) {
                        HStack(alignment: .top, spacing: 12) {
                            Image(systemName: "doc.badge.plus")
                                .font(.system(size: 18, weight: .semibold))
                                .foregroundStyle(CueTheme.signal)
                                .frame(width: 38, height: 38)
                                .background(CueTheme.signalSoft)
                                .clipShape(Circle())
                            VStack(alignment: .leading, spacing: 3) {
                                Text("Add your slides")
                                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                    .foregroundStyle(CueTheme.ink)
                                Text("PowerPoint (.pptx) or PDF · processed locally")
                                    .font(.cueCaption)
                                    .foregroundStyle(CueTheme.secondaryInk)
                            }
                        }
                        Button {
                            presentationImporterPresented = true
                        } label: {
                            Label("Choose file", systemImage: "folder")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .frame(maxWidth: .infinity, minHeight: 44)
                        }
                        .buttonStyle(.bordered)
                        .tint(CueTheme.signal)
                    }
                } else {
                    importedPresentationHeader
                    Divider().overlay(CueTheme.border)
                    VStack(alignment: .leading, spacing: 12) {
                        Text("Slide timing")
                            .font(.system(.subheadline, design: .rounded, weight: .semibold))
                            .foregroundStyle(CueTheme.ink)
                        timingModeRow(
                            mode: .even,
                            title: "Simple timing",
                            detail: evenTimingDescription,
                            disabled: false
                        )
                        timingModeRow(
                            mode: .perSlide,
                            title: "Advanced timing",
                            detail: "Set the time for each slide",
                            disabled: !canAllocateEverySlide
                        )
                        if !canAllocateEverySlide {
                            Label(
                                "Each slide needs at least one second.",
                                systemImage: "timer"
                            )
                            .font(.cueCaption)
                            .foregroundStyle(CueTheme.red)
                        }
                        if timingMode == .perSlide, canAllocateEverySlide {
                            NavigationLink {
                                SlideTimingEditorView(
                                    slides: importedSlides,
                                    durationsSeconds: $customSlideDurations,
                                    targetDurationSeconds: targetDurationSeconds
                                )
                            } label: {
                                HStack(spacing: 10) {
                                    Image(systemName: "slider.horizontal.3")
                                    Text("Edit slide timing")
                                    Spacer(minLength: 8)
                                    Text(customTimingTotal.clockString)
                                        .monospacedDigit()
                                    Image(systemName: "chevron.right")
                                        .font(.caption.weight(.semibold))
                                }
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .foregroundStyle(timingTotalIsValid ? CueTheme.signal : CueTheme.red)
                                .frame(maxWidth: .infinity, minHeight: 44)
                            }
                            .buttonStyle(.plain)
                        }
                    }
                    Divider().overlay(CueTheme.border)
                    Toggle(isOn: $transitionCueEnabled) {
                        VStack(alignment: .leading, spacing: 3) {
                            Text("Slide transition cue")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .foregroundStyle(CueTheme.ink)
                            Text(presentationCueDescription)
                                .font(.cueCaption)
                                .foregroundStyle(CueTheme.secondaryInk)
                        }
                    }
                    .tint(CueTheme.signal)
                }

                if let presentationImportError {
                    Label(presentationImportError, systemImage: "exclamationmark.circle.fill")
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.red)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
    }

    private var importedPresentationHeader: some View {
        HStack(alignment: .top, spacing: 12) {
            Image(systemName: "rectangle.stack.fill")
                .font(.system(size: 17, weight: .semibold))
                .foregroundStyle(CueTheme.signal)
                .frame(width: 38, height: 38)
                .background(CueTheme.signalSoft)
                .clipShape(Circle())
            VStack(alignment: .leading, spacing: 3) {
                Text(importedFileName ?? "Presentation")
                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                    .foregroundStyle(CueTheme.ink)
                    .lineLimit(dynamicTypeSize.isAccessibilitySize ? nil : 2)
                Text("\(importedSlides.count) slides · stays on this iPhone")
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)
            }
            Spacer(minLength: 6)
            Menu {
                Button("Replace file", systemImage: "arrow.triangle.2.circlepath") {
                    presentationImporterPresented = true
                }
                Button("Remove", systemImage: "trash", role: .destructive) {
                    removePresentation()
                }
            } label: {
                Image(systemName: "ellipsis")
                    .frame(width: 44, height: 44)
                    .contentShape(Rectangle())
            }
            .tint(CueTheme.signal)
        }
    }

    private func timingModeRow(
        mode: PresentationTimingMode,
        title: String,
        detail: String,
        disabled: Bool
    ) -> some View {
        Button {
            guard !disabled else { return }
            timingMode = mode
            if mode == .even { resetCustomTimingEvenly() }
        } label: {
            HStack(spacing: 11) {
                Image(systemName: timingMode == mode ? "checkmark.circle.fill" : "circle")
                    .foregroundStyle(timingMode == mode ? CueTheme.signal : CueTheme.border)
                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                        .foregroundStyle(CueTheme.ink)
                    Text(detail)
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.secondaryInk)
                        .fixedSize(horizontal: false, vertical: true)
                }
                Spacer(minLength: 4)
            }
            .frame(maxWidth: .infinity, minHeight: 44, alignment: .leading)
        }
        .buttonStyle(.plain)
        .disabled(disabled)
        .opacity(disabled ? 0.5 : 1)
        .accessibilityAddTraits(timingMode == mode ? .isSelected : [])
    }

    private var evenTimingDescription: String {
        simplePresentationTimingDescription(
            targetDurationSeconds: targetDurationSeconds,
            slideCount: importedSlides.count
        )
    }

    private var presentationCueDescription: String {
        let pattern = model.hapticPreferences.patternByCue[.deckBehind] ?? .longShortLong
        let intensity = model.hapticPreferences.intensityByCue[.deckBehind] ?? .medium
        return "\(pattern.label) · \(intensity.label)"
    }

    private var customTimingTotal: TimeInterval {
        TimeInterval(customSlideDurations.reduce(0, +))
    }

    private var canAllocateEverySlide: Bool {
        importedSlides.isEmpty || targetDurationSeconds >= importedSlides.count
    }

    private var timingTotalIsValid: Bool {
        timingMode == .even || Int(customTimingTotal) == targetDurationSeconds
    }

    private var targetDurationSeconds: Int {
        Int(targetMinutes * 60)
    }

    private var preparedDeckPlan: DeckPlan? {
        guard sessionMode == .powerPoint, !importedSlides.isEmpty else { return nil }
        let allocation: DeckTimingAllocation
        switch timingMode {
        case .even:
            allocation = .even(totalSeconds: targetDurationSeconds)
        case .perSlide:
            guard customSlideDurations.count == importedSlides.count else { return nil }
            allocation = .perSlide(
                durations: zip(importedSlides, customSlideDurations).map { slide, duration in
                    DeckSlideDuration(slideIndex: slide.index, durationSeconds: duration)
                },
                totalSeconds: targetDurationSeconds
            )
        }
        return try? buildTimedDeckPlan(
            title: importedFileName ?? "Presentation",
            slides: importedSlides,
            allocation: allocation
        )
    }

    private var presentationContentTypes: [UTType] {
        [
            .pdf,
            UTType(importedAs: "org.openxmlformats.presentationml.presentation"),
        ]
    }

    private func handlePresentationImport(_ result: Result<[URL], Error>) {
        switch result {
        case let .success(urls):
            guard let url = urls.first else { return }
            importPresentation(url: url)
        case .failure:
            presentationImportError = presentationImportFailureMessage(
                errorDescription: "The file picker could not open that presentation.",
                retainsCurrentPresentation: !importedSlides.isEmpty
            )
        }
    }

    private func importPresentation(url: URL) {
        presentationImportError = nil
        isImportingPresentation = true
        Task {
            let hasSecurityAccess = url.startAccessingSecurityScopedResource()
            defer {
                if hasSecurityAccess { url.stopAccessingSecurityScopedResource() }
            }
            do {
                let slides = try await Task.detached(priority: .userInitiated) {
                    try PresentationFileParser(limits: .production).parse(url: url)
                }.value
                let nextGeneratedName = url.deletingPathExtension().lastPathComponent
                importedSlides = slides
                importedFileName = nextGeneratedName
                if name == "Practice Session"
                    || name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                    || name == autoGeneratedSessionName {
                    name = nextGeneratedName
                    autoGeneratedSessionName = nextGeneratedName
                }
                if targetDurationSeconds < slides.count {
                    timingMode = .even
                }
                resetCustomTimingEvenly()
                isImportingPresentation = false
                presentationImportError = nil
                AccessibilityNotification.Announcement("Presentation imported. \(slides.count) slides.").post()
            } catch let error as PresentationParserError {
                isImportingPresentation = false
                presentationImportError = presentationImportFailureMessage(
                    errorDescription: error.localizedDescription,
                    retainsCurrentPresentation: !importedSlides.isEmpty
                )
                AccessibilityNotification.Announcement("Presentation import failed.").post()
            } catch {
                isImportingPresentation = false
                presentationImportError = presentationImportFailureMessage(
                    errorDescription: "That presentation could not be read.",
                    retainsCurrentPresentation: !importedSlides.isEmpty
                )
                AccessibilityNotification.Announcement("Presentation import failed.").post()
            }
        }
    }

    private func resetCustomTimingEvenly() {
        guard !importedSlides.isEmpty,
              let plan = try? buildTimedDeckPlan(
                title: importedFileName ?? "Presentation",
                slides: importedSlides,
                allocation: .even(totalSeconds: targetDurationSeconds)
              ) else {
            customSlideDurations = []
            return
        }
        var previousTarget = 0
        customSlideDurations = plan.checkpoints.map { checkpoint in
            defer { previousTarget = checkpoint.targetCumulativeSeconds }
            return checkpoint.targetCumulativeSeconds - previousTarget
        }
    }

    private func removePresentation() {
        if name == autoGeneratedSessionName {
            name = "Practice Session"
        }
        autoGeneratedSessionName = nil
        importedFileName = nil
        importedSlides = []
        customSlideDurations = []
        presentationImportError = nil
    }

    private var coachingOptionsToggle: some View {
        Button {
            withAnimation(CueMotion.quick(reduceMotion: reduceMotion)) {
                coachingOptionsExpanded.toggle()
            }
        } label: {
            PremiumCard(padding: 20) {
                HStack(spacing: 12) {
                    VStack(alignment: .leading, spacing: 3) {
                        CueSectionLabel(text: "Coaching options", color: CueTheme.signal)
                        Text("Pace, filler, and overtime settings")
                            .font(.cueCaption)
                            .foregroundStyle(CueTheme.secondaryInk)
                    }
                    Spacer(minLength: 8)
                    Image(systemName: coachingOptionsExpanded ? "chevron.up" : "chevron.down")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(CueTheme.signal)
                }
            }
        }
        .buttonStyle(.plain)
        .accessibilityLabel(coachingOptionsExpanded ? "Hide coaching options" : "Show coaching options")
    }

    private var paceCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 18) {
                HStack(alignment: .firstTextBaseline, spacing: 12) {
                    CueSectionLabel(text: "Pace range", color: CueTheme.signal)
                    Spacer(minLength: 8)
                    Text("\(Int(minimumWPM))–\(Int(maximumWPM)) WPM")
                        .font(.system(.subheadline, design: .rounded, weight: .semibold).monospacedDigit())
                        .foregroundStyle(paceRangeIsValid ? CueTheme.ink : CueTheme.red)
                }
                VStack(spacing: 15) {
                    labeledSlider(label: "Minimum", value: $minimumWPM, range: 90...150)
                    labeledSlider(label: "Maximum", value: $maximumWPM, range: 140...210)
                }
                Text(
                    paceRangeIsValid
                        ? "A rolling window prevents one rushed sentence from triggering a cue."
                        : "Maximum pace must be higher than minimum pace."
                )
                .font(.cueCaption)
                .foregroundStyle(paceRangeIsValid ? CueTheme.secondaryInk : CueTheme.red)
            }
        }
    }

    private func labeledSlider(label: String, value: Binding<Double>, range: ClosedRange<Double>) -> some View {
        VStack(alignment: .leading, spacing: 7) {
            HStack {
                Text(label)
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)
                Spacer()
                Text("\(Int(value.wrappedValue)) WPM")
                    .font(.cueCaption.monospacedDigit())
                    .foregroundStyle(CueTheme.ink)
            }
            Slider(value: value, in: range, step: 5)
                .tint(CueTheme.signal)
                .accessibilityLabel("\(label) speaking pace")
                .accessibilityValue("\(Int(value.wrappedValue)) words per minute")
        }
    }

    private var cueCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 16) {
                HStack(alignment: .firstTextBaseline, spacing: 12) {
                    CueSectionLabel(text: "Haptic cues", color: CueTheme.signal)
                    Spacer(minLength: 8)
                    Text("Essentials")
                        .font(.cueCaption.weight(.semibold))
                        .foregroundStyle(CueTheme.signal)
                }

                ForEach(CueKind.essentialDefaults, id: \.self) { cue in
                    cueToggle(cue)
                }

                DisclosureGroup(isExpanded: $advancedCuesExpanded) {
                    VStack(spacing: 14) {
                        ForEach(CueKind.advanced, id: \.self) { cue in
                            cueToggle(cue)
                        }
                    }
                    .padding(.top, 14)
                } label: {
                    Text("Advanced cues")
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                        .foregroundStyle(CueTheme.ink)
                }
                .tint(CueTheme.signal)

                NavigationLink {
                    HapticCueSettingsView()
                } label: {
                    HStack(spacing: 10) {
                        Image(systemName: "waveform.path")
                        Text("Customize cue behavior")
                        Spacer(minLength: 8)
                        Image(systemName: "chevron.right")
                            .font(.caption.weight(.semibold))
                    }
                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                    .foregroundStyle(CueTheme.signal)
                    .frame(maxWidth: .infinity, minHeight: 44)
                }
                .buttonStyle(.plain)

                if enabledCues.isEmpty {
                    Label("Analytics will continue without wrist cues.", systemImage: "chart.xyaxis.line")
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.secondaryInk)
                }
            }
        }
    }

    private func cueToggle(_ cue: CueKind) -> some View {
        Toggle(isOn: cueBinding(cue)) {
            HStack(spacing: 12) {
                Image(systemName: symbol(for: cue))
                    .font(.system(size: 16, weight: .medium))
                    .foregroundStyle(CueTheme.signal)
                    .frame(width: 32, height: 32)
                    .background(CueTheme.signalSoft)
                    .clipShape(Circle())
                VStack(alignment: .leading, spacing: 2) {
                    Text(cue.label)
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                        .foregroundStyle(CueTheme.ink)
                    Text(patternDescription(for: cue))
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.secondaryInk)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
        .tint(CueTheme.signal)
    }

    private var overtimeSafetyCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 14) {
                CueSectionLabel(text: "Overtime safety", color: CueTheme.signal)
                Toggle(isOn: $emergencyBuzzerEnabled) {
                    HStack(alignment: .top, spacing: 12) {
                        Image(systemName: "speaker.wave.3.fill")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundStyle(emergencyBuzzerEnabled ? CueTheme.red : CueTheme.secondaryInk)
                            .frame(width: 32, height: 32)
                            .background(
                                emergencyBuzzerEnabled
                                    ? CueTheme.red.opacity(0.10)
                                    : CueTheme.canvas.opacity(0.72)
                            )
                            .clipShape(Circle())
                        VStack(alignment: .leading, spacing: 3) {
                            Text("Emergency buzzer")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .foregroundStyle(CueTheme.ink)
                            Text("One 2-second tone at 30 seconds overtime")
                                .font(.cueCaption)
                                .foregroundStyle(CueTheme.secondaryInk)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }
                }
                .tint(CueTheme.red)

                if emergencyBuzzerEnabled {
                    Label(
                        emergencyBuzzerReadinessText,
                        systemImage: emergencyBuzzerFirmwareSupported
                            ? "info.circle.fill"
                            : "exclamationmark.circle"
                    )
                    .font(.cueCaption.weight(.semibold))
                    .foregroundStyle(emergencyBuzzerFirmwareSupported ? CueTheme.signal : CueTheme.red)
                    .transition(.opacity.combined(with: .move(edge: .top)))
                }
            }
            .animation(.easeOut(duration: 0.18), value: emergencyBuzzerEnabled)
        }
    }

    private var preflightCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 14) {
                CueSectionLabel(text: "Preflight", color: CueTheme.signal)
                preflightRow(
                    label: model.demoMode ? "Audio source" : "Phone microphone",
                    detail: model.demoMode ? "Deterministic simulation" : "Permission checked when you begin",
                    state: model.demoMode ? .ready : .pending
                )
                preflightRow(label: "Cue Band", detail: bandPreflightDetail, state: bandPreflightState)
                if sessionMode == .powerPoint {
                    preflightRow(
                        label: "Presentation",
                        detail: presentationPreflightDetail,
                        state: preparedDeckPlan == nil ? .required : .ready
                    )
                }
                if !isCueReady {
                    Button {
                        model.connectCueBand()
                    } label: {
                        Label("Connect Cue Band", systemImage: "wave.3.right")
                            .font(.system(.subheadline, design: .rounded, weight: .semibold))
                            .frame(maxWidth: .infinity, minHeight: 44)
                    }
                    .buttonStyle(.bordered)
                    .tint(CueTheme.signal)
                    .disabled(bandConnectionIsBusy)
                }
            }
        }
    }

    private func preflightRow(label: String, detail: String, state: PreflightState) -> some View {
        HStack(alignment: .top, spacing: 11) {
            Image(systemName: state.symbol)
                .font(.system(size: 15, weight: .semibold))
                .foregroundStyle(state.color)
                .frame(width: 22)
            VStack(alignment: .leading, spacing: 2) {
                Text(label)
                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                    .foregroundStyle(CueTheme.ink)
                Text(detail)
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)
                    .fixedSize(horizontal: false, vertical: true)
            }
            Spacer(minLength: 4)
        }
        .accessibilityElement(children: .combine)
    }

    private var isCueReady: Bool {
        if case .ready = model.connectionState { return true }
        return false
    }

    private var bandConnectionIsBusy: Bool {
        switch model.connectionState {
        case .searching, .connecting, .discovering, .reconnecting: true
        default: false
        }
    }

    private var bandPreflightState: PreflightState {
        if isCueReady, emergencyBuzzerEnabled, !emergencyBuzzerFirmwareSupported {
            return .required
        }
        if isCueReady {
            return enabledCues.isEmpty && !emergencyBuzzerEnabled ? .optional : .ready
        }
        if bandConnectionIsBusy { return .pending }
        if emergencyBuzzerEnabled { return .required }
        return .optional
    }

    private var bandPreflightDetail: String {
        if isCueReady, emergencyBuzzerEnabled, !emergencyBuzzerFirmwareSupported {
            return "Connected · firmware 1.3 required"
        }
        if isCueReady, enabledCues.isEmpty, emergencyBuzzerEnabled {
            return "Connected for the overtime buzzer"
        }
        if isCueReady, enabledCues.isEmpty { return "Connected · all band cues are off" }
        if isCueReady, emergencyBuzzerEnabled { return "Connected for haptics and overtime buzzer" }
        if isCueReady { return "Connected for live haptics" }
        if bandConnectionIsBusy { return model.connectionState.label }
        if emergencyBuzzerEnabled { return "Required for the emergency buzzer" }
        if sessionMode == .powerPoint,
           let presentationDetail = disconnectedPresentationBandDetail(
               transitionCueEnabled: transitionCueEnabled
           ) {
            return presentationDetail
        }
        return "Optional · analytics continue without it"
    }

    private var paceRangeIsValid: Bool {
        minimumWPM < maximumWPM
    }

    private var willUseCueBand: Bool {
        isCueReady && (!enabledCues.isEmpty || emergencyBuzzerEnabled)
    }

    private var beginButtonTitle: String {
        if sessionMode == .powerPoint {
            return "Begin presentation"
        }
        return willUseCueBand ? "Begin with Cue Band" : "Begin analytics only"
    }

    private var startDisabled: Bool {
        startDisabledReason != nil
    }

    private var startDisabledReason: String? {
        if name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return "Add a session name to continue."
        }
        if !paceRangeIsValid {
            return "Set a valid pace range to continue."
        }
        if sessionMode == .powerPoint, isImportingPresentation {
            return "Wait for the presentation to finish importing."
        }
        if sessionMode == .powerPoint, importedSlides.isEmpty {
            return "Choose a PowerPoint (.pptx) or PDF to continue."
        }
        if sessionMode == .powerPoint, timingMode == .perSlide, !timingTotalIsValid {
            return "Slide times must add up to \(TimeInterval(targetDurationSeconds).clockString)."
        }
        if sessionMode == .powerPoint, preparedDeckPlan == nil {
            return "Increase the target time so every slide receives at least one second."
        }
        if emergencyBuzzerEnabled, !isCueReady {
            return "Connect a Cue Band or turn off the emergency buzzer."
        }
        if emergencyBuzzerEnabled, !emergencyBuzzerFirmwareSupported {
            return "Flash Cue Band firmware 1.3 or turn off the emergency buzzer."
        }
        return nil
    }

    private var emergencyBuzzerFirmwareSupported: Bool {
        guard isCueReady, let status = model.lastBandStatus else { return false }
        return CueBLE.supportsEmergencyBuzzer(
            firmwareMajor: status.firmwareMajor,
            firmwareMinor: status.firmwareMinor
        )
    }

    private var emergencyBuzzerReadinessText: String {
        if emergencyBuzzerFirmwareSupported {
            return "Firmware supports D9 · test the buzzer before presenting"
        }
        if isCueReady {
            return "Connected band requires firmware 1.3 or newer"
        }
        return "Connect Cue Band before you begin"
    }

    private func cueBinding(_ cue: CueKind) -> Binding<Bool> {
        Binding(
            get: { enabledCues.contains(cue) },
            set: { enabled in
                model.setCueEnabled(cue, enabled: enabled)
            }
        )
    }

    private var enabledCues: Set<CueKind> {
        var cues = model.hapticPreferences.enabledCues
        if sessionMode == .powerPoint, transitionCueEnabled {
            cues.insert(.deckBehind)
        } else {
            cues.remove(.deckBehind)
        }
        return cues
    }

    private var presentationPreflightDetail: String {
        guard !importedSlides.isEmpty else { return "No file selected" }
        let timing = timingMode == .even ? "simple timing" : "advanced timing"
        return "\(importedSlides.count) slides · \(timing) · on-device"
    }

    private func symbol(for cue: CueKind) -> String {
        switch cue {
        case .tooFast: "hare"
        case .tooSlow: "tortoise"
        case .fillerBurst: "ellipsis.bubble"
        case .deckBehind: "rectangle.stack.badge.play"
        case .time50, .time75, .time90, .time100: "timer"
        }
    }

    private func patternDescription(for cue: CueKind) -> String {
        let pattern = model.hapticPreferences.patternByCue[cue] ?? .doubleTap
        let intensity = model.hapticPreferences.intensityByCue[cue] ?? .medium
        if cue == .fillerBurst {
            let cluster = model.hapticPreferences.fillerClusterConfiguration
            return "\(pattern.label) · \(intensity.label) · \(cluster.requiredFillerCount) in \(cluster.windowSeconds) sec"
        }
        return "\(pattern.label) · \(intensity.label)"
    }

    private func begin() {
        let deckPlan = sessionMode == .powerPoint ? preparedDeckPlan : nil
        guard sessionMode != .powerPoint || deckPlan != nil else { return }
        let baseProfile = CoachingProfile.rehearsalV1()
        let haptics = model.hapticPreferences
        let profile = CoachingProfile(
            minimumWPM: minimumWPM,
            maximumWPM: maximumWPM,
            enabledCues: enabledCues,
            patternByCue: haptics.patternByCue,
            intensityByCue: haptics.intensityByCue,
            fillerClusterConfiguration: haptics.fillerClusterConfiguration,
            highConfidenceFillers: baseProfile.highConfidenceFillers,
            optionalFillers: baseProfile.optionalFillers
        )
        let configuration = SessionConfiguration(
            id: UUID(),
            name: name.trimmingCharacters(in: .whitespacesAndNewlines),
            mode: sessionMode,
            targetDurationSeconds: TimeInterval(targetDurationSeconds),
            profile: profile,
            deckPlan: deckPlan,
            emergencyBuzzerEnabled: emergencyBuzzerEnabled
        )
        model.beginSession(configuration: configuration)
    }
}

private enum PresentationTimingMode: String, CaseIterable {
    case even
    case perSlide
}

private enum PreflightState {
    case ready
    case pending
    case required
    case optional

    var symbol: String {
        switch self {
        case .ready: "checkmark.circle.fill"
        case .pending: "clock.fill"
        case .required: "exclamationmark.circle.fill"
        case .optional: "minus.circle.fill"
        }
    }

    var color: Color {
        switch self {
        case .ready: CueTheme.green
        case .pending: CueTheme.signal
        case .required: CueTheme.red
        case .optional: CueTheme.secondaryInk
        }
    }
}
