import SwiftUI
import UniformTypeIdentifiers
import VoxaCore

func boundedSessionName(_ name: String) -> String {
    String(name.prefix(80))
}

func presentationSessionName(from url: URL) -> String {
    boundedSessionName(url.deletingPathExtension().lastPathComponent)
}
import VoxaRuntime

func presentationImportFailureMessage(
    errorDescription: String,
    retainsCurrentPresentation: Bool
) -> String {
    let trimmedDescription = errorDescription.trimmingCharacters(in: .whitespacesAndNewlines)
    guard retainsCurrentPresentation else { return trimmedDescription }
    let sentence = trimmedDescription.hasSuffix(".")
        ? trimmedDescription
        : "\(trimmedDescription)."
    return "\(sentence) Your current presentation is unchanged."
}

func simplePresentationTimingDescription(
    targetDurationSeconds: Int,
    slideCount: Int
) -> String {
    guard slideCount > 0 else { return "Divide the target evenly" }
    guard targetDurationSeconds >= slideCount else {
        let minimumMinutes = Int(ceil(Double(slideCount) / 60))
        return "Increase target to at least \(minimumMinutes) min"
    }
    let average = Double(targetDurationSeconds) / Double(slideCount)
    return "Divide evenly · about \(TimeInterval(average).clockString) per slide"
}

enum SpeakingPacePreset: String, CaseIterable, Equatable {
    case slow
    case normal
    case fast

    var label: String {
        switch self {
        case .slow: "Slow"
        case .normal: "Normal"
        case .fast: "Fast"
        }
    }

    var range: ClosedRange<Double> {
        switch self {
        case .slow: 100...130
        case .normal: 130...160
        case .fast: 160...190
        }
    }

    static func matching(minimumWPM: Double, maximumWPM: Double) -> SpeakingPacePreset? {
        allCases.first { preset in
            preset.range.lowerBound == minimumWPM && preset.range.upperBound == maximumWPM
        }
    }
}

func hapticPatternPulseDescription(_ pattern: HapticPattern) -> String {
    switch pattern {
    case .doubleTap: "2 short pulses"
    case .longPulse: "1 long pulse"
    case .tripleTap: "3 quick pulses"
    case .longShortLong: "Long, short, long pulses"
    case .singlePulse: "1 firm pulse"
    case .doublePulse: "2 firm pulses"
    case .triplePulse: "3 firm pulses"
    case .calmWave: "1 gradual pulse"
    case .deadlineHold: "1 sustained pulse"
    }
}

struct SessionSetupView: View {
    @Environment(AppModel.self) private var model
    @Environment(\.dismiss) private var dismiss
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @Environment(\.dynamicTypeSize) private var dynamicTypeSize
    @State private var sessionMode: SessionMode
    @State private var name = "Practice Session"
    @State private var targetMinutes = 5.0
    @State private var minimumWPM = 130.0
    @State private var maximumWPM = 160.0
    @State private var advancedPaceExpanded = false
    @State private var advancedCuesExpanded = false
    @State private var presentationImporterPresented = false
    @State private var isImportingPresentation = false
    @State private var importedFileName: String?
    @State private var importedSlides: [DeckSlide] = []
    @State private var presentationImportError: String?
    @State private var timingMode = PresentationTimingMode.even
    @State private var customSlideDurations: [Int] = []
    @State private var transitionCueEnabled = true
    @State private var coachingOptionsExpanded = false
    @State private var autoGeneratedSessionName: String?
    @State private var previewedCue: CueKind?

    init(initialMode: SessionMode) {
        _sessionMode = State(initialValue: initialMode)
    }

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    sessionTypeCard
                    basicsCard
                    if sessionMode == .powerPoint {
                        presentationCard
                        coachingOptionsToggle
                        if coachingOptionsExpanded {
                            paceCard
                            cueCard
                        }
                    } else {
                        paceCard
                        cueCard
                    }
                    preflightCard
                    VStack(alignment: .leading, spacing: 9) {
                        VoxaButton(
                            title: beginButtonTitle,
                            symbol: "arrow.up.right",
                            style: .primary,
                            disabled: startDisabled,
                            action: begin
                        )
                        if let startDisabledReason {
                            Label(startDisabledReason, systemImage: "info.circle")
                                .font(.cueCaption)
                                .foregroundStyle(CueTheme.secondaryInk)
                                .padding(.horizontal, 4)
                        }
                    }
                }
                .padding(.horizontal, 20)
                .padding(.vertical, 22)
            }
            .background(CueTheme.canvas)
            .navigationTitle("Session setup")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
            }
            .fileImporter(
                isPresented: $presentationImporterPresented,
                allowedContentTypes: presentationContentTypes,
                allowsMultipleSelection: false,
                onCompletion: handlePresentationImport
            )
            .onChange(of: targetMinutes) { _, _ in
                if !canAllocateEverySlide {
                    timingMode = .even
                }
                if timingMode == .even { resetCustomTimingEvenly() }
            }
        }
    }

    private var sessionTypeCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 14) {
                CueSectionLabel(text: "Session type", color: CueTheme.signal)
                sessionTypeRow(
                    mode: .freeSpeaking,
                    title: "Free speaking",
                    detail: "Pace, fillers, and overall timing",
                    symbol: "waveform"
                )
                sessionTypeRow(
                    mode: .powerPoint,
                    title: "Presentation",
                    detail: "Add timed cues for every slide",
                    symbol: "rectangle.stack"
                )
            }
        }
    }

    private func sessionTypeRow(
        mode: SessionMode,
        title: String,
        detail: String,
        symbol: String
    ) -> some View {
        Button {
            withAnimation(CueMotion.quick(reduceMotion: reduceMotion)) {
                sessionMode = mode
            }
        } label: {
            HStack(spacing: 12) {
                Image(systemName: symbol)
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundStyle(sessionMode == mode ? Color.white : CueTheme.signal)
                    .frame(width: 36, height: 36)
                    .background(sessionMode == mode ? CueTheme.signal : CueTheme.signalSoft)
                    .clipShape(Circle())
                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                        .foregroundStyle(CueTheme.ink)
                    Text(detail)
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.secondaryInk)
                }
                Spacer(minLength: 8)
                Image(systemName: sessionMode == mode ? "checkmark.circle.fill" : "circle")
                    .foregroundStyle(sessionMode == mode ? CueTheme.signal : CueTheme.border)
            }
            .padding(12)
            .background(sessionMode == mode ? CueTheme.signalSoft.opacity(0.72) : CueTheme.canvas.opacity(0.6))
            .clipShape(RoundedRectangle(cornerRadius: CueTheme.Radius.small, style: .continuous))
        }
        .buttonStyle(.plain)
        .accessibilityAddTraits(sessionMode == mode ? .isSelected : [])
    }

    private var basicsCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 18) {
                setupSectionTitle("Session")
                VStack(alignment: .leading, spacing: 8) {
                    Label("Session name", systemImage: "pencil")
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.secondaryInk)
                    HStack(spacing: 10) {
                        TextField(
                            "Name this session",
                            text: Binding(
                                get: { name },
                                set: { name = boundedSessionName($0) }
                            )
                        )
                            .font(.system(.body, design: .rounded, weight: .semibold))
                            .textInputAutocapitalization(.sentences)
                            .submitLabel(.done)
                        Image(systemName: "square.and.pencil")
                            .font(.system(size: 15, weight: .semibold))
                            .foregroundStyle(CueTheme.signal)
                            .accessibilityHidden(true)
                    }
                    .padding(15)
                    .background(CueTheme.canvas.opacity(0.72))
                    .clipShape(RoundedRectangle(cornerRadius: CueTheme.Radius.small, style: .continuous))
                    .overlay {
                        RoundedRectangle(cornerRadius: CueTheme.Radius.small, style: .continuous)
                            .stroke(CueTheme.signal.opacity(0.34), lineWidth: 1)
                    }
                }

                Stepper(value: $targetMinutes, in: 1...30, step: 1) {
                    if dynamicTypeSize.isAccessibilitySize {
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Target duration")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .foregroundStyle(CueTheme.ink)
                            Text("\(Int(targetMinutes)) minutes")
                                .font(.cueCaption.monospacedDigit())
                                .foregroundStyle(CueTheme.signal)
                        }
                    } else {
                        HStack(spacing: 12) {
                            VStack(alignment: .leading, spacing: 4) {
                                Text("Target duration")
                                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                    .foregroundStyle(CueTheme.ink)
                                Text("Drives private timing reminders")
                                    .font(.cueCaption)
                                    .foregroundStyle(CueTheme.secondaryInk)
                            }
                            Spacer(minLength: 8)
                            Text("\(Int(targetMinutes)) min")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold).monospacedDigit())
                                .foregroundStyle(CueTheme.signal)
                        }
                    }
                }
            }
        }
    }

    private var presentationCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 17) {
                CueSectionLabel(text: "Presentation", color: CueTheme.signal)

                if isImportingPresentation {
                    HStack(spacing: 12) {
                        ProgressView()
                            .tint(CueTheme.signal)
                        Text("Reading slides on this iPhone…")
                            .font(.system(.subheadline, design: .rounded, weight: .semibold))
                            .foregroundStyle(CueTheme.ink)
                    }
                    .frame(maxWidth: .infinity, minHeight: 64, alignment: .leading)
                } else if importedSlides.isEmpty {
                    VStack(alignment: .leading, spacing: 12) {
                        HStack(alignment: .top, spacing: 12) {
                            Image(systemName: "doc.badge.plus")
                                .font(.system(size: 18, weight: .semibold))
                                .foregroundStyle(CueTheme.signal)
                                .frame(width: 38, height: 38)
                                .background(CueTheme.signalSoft)
                                .clipShape(Circle())
                            VStack(alignment: .leading, spacing: 3) {
                                Text("Add your slides")
                                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                    .foregroundStyle(CueTheme.ink)
                                Text("PowerPoint (.pptx) or PDF · processed locally")
                                    .font(.cueCaption)
                                    .foregroundStyle(CueTheme.secondaryInk)
                            }
                        }
                        Button {
                            presentationImporterPresented = true
                        } label: {
                            Label("Choose file", systemImage: "folder")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .frame(maxWidth: .infinity, minHeight: 44)
                        }
                        .buttonStyle(.bordered)
                        .tint(CueTheme.signal)
                    }
                } else {
                    importedPresentationHeader
                    Divider().overlay(CueTheme.border)
                    VStack(alignment: .leading, spacing: 12) {
                        Text("Slide timing")
                            .font(.system(.subheadline, design: .rounded, weight: .semibold))
                            .foregroundStyle(CueTheme.ink)
                        timingModeRow(
                            mode: .even,
                            title: "Simple timing",
                            detail: evenTimingDescription,
                            disabled: false
                        )
                        timingModeRow(
                            mode: .perSlide,
                            title: "Advanced timing",
                            detail: "Set the time for each slide",
                            disabled: !canAllocateEverySlide
                        )
                        if !canAllocateEverySlide {
                            Label(
                                "Each slide needs at least one second.",
                                systemImage: "timer"
                            )
                            .font(.cueCaption)
                            .foregroundStyle(CueTheme.red)
                        }
                        if timingMode == .perSlide, canAllocateEverySlide {
                            NavigationLink {
                                SlideTimingEditorView(
                                    slides: importedSlides,
                                    durationsSeconds: $customSlideDurations,
                                    targetDurationSeconds: targetDurationSeconds
                                )
                            } label: {
                                HStack(spacing: 10) {
                                    Image(systemName: "slider.horizontal.3")
                                    Text("Edit slide timing")
                                    Spacer(minLength: 8)
                                    Text(customTimingTotal.clockString)
                                        .monospacedDigit()
                                    Image(systemName: "chevron.right")
                                        .font(.caption.weight(.semibold))
                                }
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .foregroundStyle(timingTotalIsValid ? CueTheme.signal : CueTheme.red)
                                .frame(maxWidth: .infinity, minHeight: 44)
                            }
                            .buttonStyle(.plain)
                        }
                    }
                    Divider().overlay(CueTheme.border)
                    Toggle(isOn: $transitionCueEnabled) {
                        VStack(alignment: .leading, spacing: 3) {
                            Text("Slide transition cue")
                                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                                .foregroundStyle(CueTheme.ink)
                            Text(presentationCueDescription)
                                .font(.cueCaption)
                                .foregroundStyle(CueTheme.secondaryInk)
                        }
                    }
                    .tint(CueTheme.signal)
                }

                if let presentationImportError {
                    Label(presentationImportError, systemImage: "exclamationmark.circle.fill")
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.red)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
    }

    private var importedPresentationHeader: some View {
        HStack(alignment: .top, spacing: 12) {
            Image(systemName: "rectangle.stack.fill")
                .font(.system(size: 17, weight: .semibold))
                .foregroundStyle(CueTheme.signal)
                .frame(width: 38, height: 38)
                .background(CueTheme.signalSoft)
                .clipShape(Circle())
            VStack(alignment: .leading, spacing: 3) {
                Text(importedFileName ?? "Presentation")
                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                    .foregroundStyle(CueTheme.ink)
                    .lineLimit(dynamicTypeSize.isAccessibilitySize ? nil : 2)
                Text("\(importedSlides.count) slides · stays on this iPhone")
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)
            }
            Spacer(minLength: 6)
            Menu {
                Button("Replace file", systemImage: "arrow.triangle.2.circlepath") {
                    presentationImporterPresented = true
                }
                Button("Remove", systemImage: "trash", role: .destructive) {
                    removePresentation()
                }
            } label: {
                Image(systemName: "ellipsis")
                    .frame(width: 44, height: 44)
                    .contentShape(Rectangle())
            }
            .tint(CueTheme.signal)
        }
    }

    private func timingModeRow(
        mode: PresentationTimingMode,
        title: String,
        detail: String,
        disabled: Bool
    ) -> some View {
        Button {
            guard !disabled else { return }
            timingMode = mode
            if mode == .even { resetCustomTimingEvenly() }
        } label: {
            HStack(spacing: 11) {
                Image(systemName: timingMode == mode ? "checkmark.circle.fill" : "circle")
                    .foregroundStyle(timingMode == mode ? CueTheme.signal : CueTheme.border)
                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                        .foregroundStyle(CueTheme.ink)
                    Text(detail)
                        .font(.cueCaption)
                        .foregroundStyle(CueTheme.secondaryInk)
                        .fixedSize(horizontal: false, vertical: true)
                }
                Spacer(minLength: 4)
            }
            .frame(maxWidth: .infinity, minHeight: 44, alignment: .leading)
        }
        .buttonStyle(.plain)
        .disabled(disabled)
        .opacity(disabled ? 0.5 : 1)
        .accessibilityAddTraits(timingMode == mode ? .isSelected : [])
    }

    private var evenTimingDescription: String {
        simplePresentationTimingDescription(
            targetDurationSeconds: targetDurationSeconds,
            slideCount: importedSlides.count
        )
    }

    private var presentationCueDescription: String {
        let pattern = model.hapticPreferences.patternByCue[.deckBehind] ?? .longShortLong
        let intensity = model.hapticPreferences.intensityByCue[.deckBehind] ?? .medium
        return "\(hapticPatternPulseDescription(pattern)) · \(intensity.label)"
    }

    private var customTimingTotal: TimeInterval {
        TimeInterval(customSlideDurations.reduce(0, +))
    }

    private var canAllocateEverySlide: Bool {
        importedSlides.isEmpty || targetDurationSeconds >= importedSlides.count
    }

    private var timingTotalIsValid: Bool {
        timingMode == .even || Int(customTimingTotal) == targetDurationSeconds
    }

    private var targetDurationSeconds: Int {
        Int(targetMinutes * 60)
    }

    private var preparedDeckPlan: DeckPlan? {
        guard sessionMode == .powerPoint, !importedSlides.isEmpty else { return nil }
        let allocation: DeckTimingAllocation
        switch timingMode {
        case .even:
            allocation = .even(totalSeconds: targetDurationSeconds)
        case .perSlide:
            guard customSlideDurations.count == importedSlides.count else { return nil }
            allocation = .perSlide(
                durations: zip(importedSlides, customSlideDurations).map { slide, duration in
                    DeckSlideDuration(slideIndex: slide.index, durationSeconds: duration)
                },
                totalSeconds: targetDurationSeconds
            )
        }
        return try? buildTimedDeckPlan(
            title: importedFileName ?? "Presentation",
            slides: importedSlides,
            allocation: allocation
        )
    }

    private var presentationContentTypes: [UTType] {
        [
            .pdf,
            UTType(importedAs: "org.openxmlformats.presentationml.presentation"),
        ]
    }

    private func handlePresentationImport(_ result: Result<[URL], Error>) {
        switch result {
        case let .success(urls):
            guard let url = urls.first else { return }
            importPresentation(url: url)
        case .failure:
            presentationImportError = presentationImportFailureMessage(
                errorDescription: "The file picker could not open that presentation.",
                retainsCurrentPresentation: !importedSlides.isEmpty
            )
        }
    }

    private func importPresentation(url: URL) {
        presentationImportError = nil
        isImportingPresentation = true
        Task {
            let hasSecurityAccess = url.startAccessingSecurityScopedResource()
            defer {
                if hasSecurityAccess { url.stopAccessingSecurityScopedResource() }
            }
            do {
                let slides = try await Task.detached(priority: .userInitiated) {
                    try PresentationFileParser(limits: .production).parse(url: url)
                }.value
                let nextGeneratedName = presentationSessionName(from: url)
                importedSlides = slides
                importedFileName = nextGeneratedName
                if name == "Practice Session"
                    || name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                    || name == autoGeneratedSessionName {
                    name = nextGeneratedName
                    autoGeneratedSessionName = nextGeneratedName
                }
                if targetDurationSeconds < slides.count {
                    timingMode = .even
                }
                resetCustomTimingEvenly()
                isImportingPresentation = false
                presentationImportError = nil
                AccessibilityNotification.Announcement("Presentation imported. \(slides.count) slides.").post()
            } catch let error as PresentationParserError {
                isImportingPresentation = false
                presentationImportError = presentationImportFailureMessage(
                    errorDescription: error.localizedDescription,
                    retainsCurrentPresentation: !importedSlides.isEmpty
                )
                AccessibilityNotification.Announcement("Presentation import failed.").post()
            } catch {
                isImportingPresentation = false
                presentationImportError = presentationImportFailureMessage(
                    errorDescription: "That presentation could not be read.",
                    retainsCurrentPresentation: !importedSlides.isEmpty
                )
                AccessibilityNotification.Announcement("Presentation import failed.").post()
            }
        }
    }

    private func resetCustomTimingEvenly() {
        guard !importedSlides.isEmpty,
              let plan = try? buildTimedDeckPlan(
                title: importedFileName ?? "Presentation",
                slides: importedSlides,
                allocation: .even(totalSeconds: targetDurationSeconds)
              ) else {
            customSlideDurations = []
            return
        }
        var previousTarget = 0
        customSlideDurations = plan.checkpoints.map { checkpoint in
            defer { previousTarget = checkpoint.targetCumulativeSeconds }
            return checkpoint.targetCumulativeSeconds - previousTarget
        }
    }

    private func removePresentation() {
        if name == autoGeneratedSessionName {
            name = "Practice Session"
        }
        autoGeneratedSessionName = nil
        importedFileName = nil
        importedSlides = []
        customSlideDurations = []
        presentationImportError = nil
    }

    private var coachingOptionsToggle: some View {
        Button {
            withAnimation(CueMotion.quick(reduceMotion: reduceMotion)) {
                coachingOptionsExpanded.toggle()
            }
        } label: {
            PremiumCard(padding: 20) {
                HStack(spacing: 12) {
                    VStack(alignment: .leading, spacing: 3) {
                        setupSectionTitle("Coaching options")
                        Text("Pace and wrist cue settings")
                            .font(.cueCaption)
                            .foregroundStyle(CueTheme.secondaryInk)
                    }
                    Spacer(minLength: 8)
                    Image(systemName: coachingOptionsExpanded ? "chevron.up" : "chevron.down")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(CueTheme.signal)
                }
            }
        }
        .buttonStyle(.plain)
        .accessibilityLabel(coachingOptionsExpanded ? "Hide coaching options" : "Show coaching options")
    }

    private var paceCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 18) {
                HStack(alignment: .center, spacing: 12) {
                    setupSectionTitle("Pace range")
                    Spacer(minLength: 8)
                    Button {
                        withAnimation(CueMotion.quick(reduceMotion: reduceMotion)) {
                            advancedPaceExpanded.toggle()
                        }
                    } label: {
                        Image(systemName: advancedPaceExpanded ? "gearshape.fill" : "gearshape")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundStyle(CueTheme.signal)
                            .frame(width: 40, height: 40)
                            .background(CueTheme.signalSoft)
                            .clipShape(Circle())
                    }
                    .buttonStyle(.plain)
                    .accessibilityLabel(advancedPaceExpanded ? "Hide custom pace range" : "Customize pace range")
                }

                Text("Choose the speaking speed you want Cue to coach.")
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)

                HStack(spacing: 8) {
                    ForEach(SpeakingPacePreset.allCases, id: \.self) { preset in
                        pacePresetButton(preset)
                    }
                }

                HStack(spacing: 6) {
                    Text(paceSelectionLabel)
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                    Text("· \(Int(minimumWPM))–\(Int(maximumWPM)) WPM")
                        .font(.cueCaption.monospacedDigit())
                    if selectedPacePreset == .normal {
                        Text("Recommended")
                            .font(.system(.caption2, design: .rounded, weight: .bold))
                            .foregroundStyle(CueTheme.signal)
                            .padding(.horizontal, 7)
                            .padding(.vertical, 4)
                            .background(CueTheme.signalSoft)
                            .clipShape(Capsule())
                    }
                }
                .foregroundStyle(paceRangeIsValid ? CueTheme.ink : CueTheme.red)
                .fixedSize(horizontal: false, vertical: true)

                if advancedPaceExpanded {
                    VStack(spacing: 15) {
                        Divider().overlay(CueTheme.border)
                        labeledSlider(label: "Minimum", value: $minimumWPM, range: 90...170)
                        labeledSlider(label: "Maximum", value: $maximumWPM, range: 120...210)
                        if !paceRangeIsValid {
                            Text("Maximum pace must be higher than minimum pace.")
                                .font(.cueCaption)
                                .foregroundStyle(CueTheme.red)
                        }
                    }
                    .transition(.opacity.combined(with: .move(edge: .top)))
                }
            }
        }
    }

    private func pacePresetButton(_ preset: SpeakingPacePreset) -> some View {
        let isSelected = selectedPacePreset == preset
        return Button {
            minimumWPM = preset.range.lowerBound
            maximumWPM = preset.range.upperBound
        } label: {
            Text(preset.label)
                .font(.system(.subheadline, design: .rounded, weight: .semibold))
                .foregroundStyle(isSelected ? Color.white : CueTheme.ink)
                .frame(maxWidth: .infinity, minHeight: 42)
                .background(isSelected ? CueTheme.signal : CueTheme.canvas.opacity(0.72))
                .clipShape(RoundedRectangle(cornerRadius: CueTheme.Radius.small, style: .continuous))
                .overlay {
                    RoundedRectangle(cornerRadius: CueTheme.Radius.small, style: .continuous)
                        .stroke(isSelected ? Color.clear : CueTheme.border, lineWidth: 0.75)
                }
        }
        .buttonStyle(.plain)
        .accessibilityAddTraits(isSelected ? .isSelected : [])
        .accessibilityValue("\(Int(preset.range.lowerBound)) to \(Int(preset.range.upperBound)) words per minute")
    }

    private var selectedPacePreset: SpeakingPacePreset? {
        SpeakingPacePreset.matching(minimumWPM: minimumWPM, maximumWPM: maximumWPM)
    }

    private var paceSelectionLabel: String {
        selectedPacePreset?.label ?? "Custom"
    }

    private func labeledSlider(label: String, value: Binding<Double>, range: ClosedRange<Double>) -> some View {
        VStack(alignment: .leading, spacing: 7) {
            HStack {
                Text(label)
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)
                Spacer()
                Text("\(Int(value.wrappedValue)) WPM")
                    .font(.cueCaption.monospacedDigit())
                    .foregroundStyle(CueTheme.ink)
            }
            Slider(value: value, in: range, step: 5)
                .tint(CueTheme.signal)
                .accessibilityLabel("\(label) speaking pace")
                .accessibilityValue("\(Int(value.wrappedValue)) words per minute")
        }
    }

    private var cueCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 16) {
                HStack(alignment: .center, spacing: 12) {
                    setupSectionTitle("Haptic cues")
                    Spacer(minLength: 8)
                    NavigationLink {
                        HapticCueSettingsView()
                    } label: {
                        Image(systemName: "gearshape")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundStyle(CueTheme.signal)
                            .frame(width: 40, height: 40)
                            .background(CueTheme.signalSoft)
                            .clipShape(Circle())
                    }
                    .buttonStyle(.plain)
                    .accessibilityLabel("Customize haptic cues")
                }

                Text("Cue sends private pulses to your wrist while you speak.")
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)

                ForEach(CueKind.essentialDefaults, id: \.self) { cue in
                    cueToggle(cue)
                }

                DisclosureGroup(isExpanded: $advancedCuesExpanded) {
                    VStack(spacing: 14) {
                        ForEach(CueKind.advanced, id: \.self) { cue in
                            cueToggle(cue)
                        }
                    }
                    .padding(.top, 14)
                } label: {
                    Text("Advanced cues")
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                        .foregroundStyle(CueTheme.ink)
                }
                .tint(CueTheme.signal)
            }
        }
    }

    private func cueToggle(_ cue: CueKind) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Toggle(isOn: cueBinding(cue)) {
                HStack(spacing: 12) {
                    Image(systemName: symbol(for: cue))
                        .font(.system(size: 16, weight: .medium))
                        .foregroundStyle(CueTheme.signal)
                        .frame(width: 32, height: 32)
                        .background(CueTheme.signalSoft)
                        .clipShape(Circle())
                    Text(cue.label)
                        .font(.system(.subheadline, design: .rounded, weight: .semibold))
                        .foregroundStyle(CueTheme.ink)
                }
            }
            .tint(CueTheme.signal)

            HStack(spacing: 10) {
                Text(patternDescription(for: cue))
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)
                    .fixedSize(horizontal: false, vertical: true)
                Spacer(minLength: 4)
                Button {
                    preview(cue)
                } label: {
                    Label(previewButtonTitle(for: cue), systemImage: "wave.3.right")
                        .font(.system(.caption, design: .rounded, weight: .semibold))
                        .frame(minWidth: 68, minHeight: 34)
                }
                .buttonStyle(.bordered)
                .tint(CueTheme.signal)
                .disabled(!isCueReady || model.deviceLabCueDelivery.isPending)
                .accessibilityLabel("Test \(cue.label) haptic cue")
            }
            .padding(.leading, 44)

            if let feedback = previewFeedback(for: cue) {
                Label(feedback.text, systemImage: feedback.symbol)
                    .font(.cueCaption)
                    .foregroundStyle(feedback.color)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding(.leading, 44)
                    .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
        .animation(CueMotion.quick(reduceMotion: reduceMotion), value: model.deviceLabCueDelivery)
    }

    private func preview(_ cue: CueKind) {
        previewedCue = cue
        model.sendDebugCue(
            pattern: model.hapticPreferences.patternByCue[cue] ?? .doubleTap,
            intensity: model.hapticPreferences.intensityByCue[cue] ?? .medium,
            repeatCount: 1
        )
    }

    private func previewButtonTitle(for cue: CueKind) -> String {
        guard previewedCue == cue else { return "Test" }
        return switch model.deviceLabCueDelivery {
        case .awaitingAcceptance, .awaitingCompletion: "Sending"
        case .completed, .rejected, .failed: "Test again"
        case .idle: "Test"
        }
    }

    private func previewFeedback(for cue: CueKind) -> (text: String, symbol: String, color: Color)? {
        guard previewedCue == cue else { return nil }
        return switch model.deviceLabCueDelivery {
        case .idle:
            nil
        case .awaitingAcceptance:
            ("Sending pulse to Cue Band…", "arrow.up.circle", CueTheme.signal)
        case .awaitingCompletion:
            ("Band accepted it. Waiting for confirmation…", "ellipsis.circle", CueTheme.signal)
        case .completed:
            ("Pulse confirmed by Cue Band", "checkmark.circle.fill", CueTheme.green)
        case .rejected:
            ("Cue Band rejected this pulse", "xmark.circle.fill", CueTheme.red)
        case let .failed(_, message):
            (message, "exclamationmark.triangle.fill", CueTheme.red)
        }
    }

    private func setupSectionTitle(_ title: String) -> some View {
        Text(title)
            .font(.cueSection)
            .foregroundStyle(CueTheme.ink)
            .accessibilityAddTraits(.isHeader)
    }

    private var preflightCard: some View {
        PremiumCard(padding: 20) {
            VStack(alignment: .leading, spacing: 14) {
                CueSectionLabel(text: "Preflight", color: CueTheme.signal)
                preflightRow(
                    label: model.demoMode ? "Audio source" : "Phone microphone",
                    detail: model.demoMode ? "Deterministic simulation" : "Permission checked when you begin",
                    state: model.demoMode ? .ready : .pending
                )
                preflightRow(label: "Cue Band", detail: bandPreflightDetail, state: bandPreflightState)
                if sessionMode == .powerPoint {
                    preflightRow(
                        label: "Presentation",
                        detail: presentationPreflightDetail,
                        state: preparedDeckPlan == nil ? .required : .ready
                    )
                }
                if !isCueReady {
                    Button {
                        model.connectCueBand()
                    } label: {
                        Label("Connect Cue Band", systemImage: "wave.3.right")
                            .font(.system(.subheadline, design: .rounded, weight: .semibold))
                            .frame(maxWidth: .infinity, minHeight: 44)
                    }
                    .buttonStyle(.bordered)
                    .tint(CueTheme.signal)
                    .disabled(bandConnectionIsBusy)
                }
            }
        }
    }

    private func preflightRow(label: String, detail: String, state: PreflightState) -> some View {
        HStack(alignment: .top, spacing: 11) {
            Image(systemName: state.symbol)
                .font(.system(size: 15, weight: .semibold))
                .foregroundStyle(state.color)
                .frame(width: 22)
            VStack(alignment: .leading, spacing: 2) {
                Text(label)
                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                    .foregroundStyle(CueTheme.ink)
                Text(detail)
                    .font(.cueCaption)
                    .foregroundStyle(CueTheme.secondaryInk)
                    .fixedSize(horizontal: false, vertical: true)
            }
            Spacer(minLength: 4)
        }
        .accessibilityElement(children: .combine)
    }

    private var isCueReady: Bool {
        if case .ready = model.connectionState { return true }
        return false
    }

    private var bandConnectionIsBusy: Bool {
        switch model.connectionState {
        case .searching, .connecting, .discovering, .reconnecting: true
        default: false
        }
    }

    private var bandPreflightState: PreflightState {
        if isCueReady { return .ready }
        if bandConnectionIsBusy { return .pending }
        return .required
    }

    private var bandPreflightDetail: String {
        if isCueReady, enabledCues.isEmpty { return "Connected · all band cues are off" }
        if isCueReady { return "Connected for live haptics" }
        if bandConnectionIsBusy { return model.connectionState.label }
        return "Reconnect Cue Band to continue"
    }

    private var paceRangeIsValid: Bool {
        minimumWPM < maximumWPM
    }

    private var beginButtonTitle: String {
        if sessionMode == .powerPoint {
            return "Begin presentation"
        }
        return "Begin session"
    }

    private var startDisabled: Bool {
        startDisabledReason != nil
    }

    private var startDisabledReason: String? {
        if !isCueReady {
            return "Reconnect Cue Band to begin."
        }
        if name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return "Add a session name to continue."
        }
        if !paceRangeIsValid {
            return "Set a valid pace range to continue."
        }
        if sessionMode == .powerPoint, isImportingPresentation {
            return "Wait for the presentation to finish importing."
        }
        if sessionMode == .powerPoint, importedSlides.isEmpty {
            return "Choose a PowerPoint (.pptx) or PDF to continue."
        }
        if sessionMode == .powerPoint, timingMode == .perSlide, !timingTotalIsValid {
            return "Slide times must add up to \(TimeInterval(targetDurationSeconds).clockString)."
        }
        if sessionMode == .powerPoint, preparedDeckPlan == nil {
            return "Increase the target time so every slide receives at least one second."
        }
        return nil
    }

    private func cueBinding(_ cue: CueKind) -> Binding<Bool> {
        Binding(
            get: { enabledCues.contains(cue) },
            set: { enabled in
                model.setCueEnabled(cue, enabled: enabled)
            }
        )
    }

    private var enabledCues: Set<CueKind> {
        var cues = model.hapticPreferences.enabledCues
        if sessionMode == .powerPoint, transitionCueEnabled {
            cues.insert(.deckBehind)
        } else {
            cues.remove(.deckBehind)
        }
        return cues
    }

    private var presentationPreflightDetail: String {
        guard !importedSlides.isEmpty else { return "No file selected" }
        let timing = timingMode == .even ? "simple timing" : "advanced timing"
        return "\(importedSlides.count) slides · \(timing) · on-device"
    }

    private func symbol(for cue: CueKind) -> String {
        switch cue {
        case .tooFast: "hare"
        case .tooSlow: "tortoise"
        case .fillerBurst: "ellipsis.bubble"
        case .deckBehind: "rectangle.stack.badge.play"
        case .time50, .time75, .time90, .time100: "timer"
        }
    }

    private func patternDescription(for cue: CueKind) -> String {
        let pattern = model.hapticPreferences.patternByCue[cue] ?? .doubleTap
        let intensity = model.hapticPreferences.intensityByCue[cue] ?? .medium
        if cue == .fillerBurst {
            let cluster = model.hapticPreferences.fillerClusterConfiguration
            return "\(hapticPatternPulseDescription(pattern)) · \(intensity.label) · \(cluster.requiredFillerCount) fillers / \(cluster.windowSeconds) sec"
        }
        return "\(hapticPatternPulseDescription(pattern)) · \(intensity.label)"
    }

    private func begin() {
        let deckPlan = sessionMode == .powerPoint ? preparedDeckPlan : nil
        guard isCueReady, sessionMode != .powerPoint || deckPlan != nil else { return }
        let baseProfile = CoachingProfile.rehearsalV1()
        let haptics = model.hapticPreferences
        let profile = CoachingProfile(
            minimumWPM: minimumWPM,
            maximumWPM: maximumWPM,
            enabledCues: enabledCues,
            patternByCue: haptics.patternByCue,
            intensityByCue: haptics.intensityByCue,
            fillerClusterConfiguration: haptics.fillerClusterConfiguration,
            highConfidenceFillers: baseProfile.highConfidenceFillers,
            optionalFillers: baseProfile.optionalFillers
        )
        let configuration = SessionConfiguration(
            id: UUID(),
            name: name.trimmingCharacters(in: .whitespacesAndNewlines),
            mode: sessionMode,
            targetDurationSeconds: TimeInterval(targetDurationSeconds),
            profile: profile,
            deckPlan: deckPlan,
            emergencyBuzzerEnabled: false
        )
        model.beginSession(configuration: configuration)
    }
}

private enum PresentationTimingMode: String, CaseIterable {
    case even
    case perSlide
}

private enum PreflightState {
    case ready
    case pending
    case required
    case optional

    var symbol: String {
        switch self {
        case .ready: "checkmark.circle.fill"
        case .pending: "clock.fill"
        case .required: "exclamationmark.circle.fill"
        case .optional: "minus.circle.fill"
        }
    }

    var color: Color {
        switch self {
        case .ready: CueTheme.green
        case .pending: CueTheme.signal
        case .required: CueTheme.red
        case .optional: CueTheme.secondaryInk
        }
    }
}
